---
title: "hw03_dplyr"
author: "Trevor Baker"
date: "30/09/2019"
output: 
  html_document:
    keep_md: true
---
<!--This is to set up the two-column and clearer output formats-->
<style type="text/css">
.twoC {width: 100%}
.clearer {clear: both}
.twoC .table {max-width: 50%; float: right}
.twoC img {max-width: 50%; float: left}
</style>

```{r setup, echo=F, warning=F, message=F}

library(gapminder)
library(tidyverse)
library(knitr)

```


### Task Option 2
##### Get the maximum and minimum of GDP per capita for all continents.

<div class="twoC">
```{r opt_2_data}
o2 <- gapminder %>%
        group_by(continent) %>%
        summarize(minGDP=min(gdpPercap) %>% round(digits=0),
                  maxGDP=max(gdpPercap) %>% round(digits=0))
```

```{r opt_2_graph}
o2g <- gapminder %>%
        group_by(continent,year) %>%
        summarize(minGDP_yr=min(gdpPercap) %>% round(digits=0),
                  maxGDP_yr=max(gdpPercap) %>% round(digits=0)) %>% #get annual min and max
        ungroup() %>%
        group_by(continent) %>%
        mutate(minGDP=min(minGDP_yr),
                  maxGDP=max(maxGDP_yr)) %>% #get overall min and max
          ggplot(aes(x=year,y=minGDP_yr, colour=continent)) +
            geom_line(linetype=2) + #annual trend
            geom_line(aes(x=year, y=maxGDP_yr, colour=continent),linetype=2) + #annual trend
            geom_line(aes(x=year,y=minGDP), size=1.5) + #overall min
            geom_line(aes(x=year,y=maxGDP), size=1.5) + #overall max
            scale_y_log10(labels=scales::dollar_format()) +
            theme(axis.text.x = element_text(angle = 90)) +
            labs(x="",
                 y="GDP per capita, US $ (inflation-adjusted)",
                 colour="Continent",
                 title="Minimum and maximum GDP per capita by continent, 1952 to 2007") +
            facet_wrap(~continent)

```

<div class="twoC">
```{r opt_2_output, echo=F}

knitr::kable(o2)
o2g

```
</div>
<div class="clearer"></div>



### Task Option 3
##### Look at the spread of GDP per capita within the continents.


```{r opt_3_data}

o3 <- gapminder %>%
        group_by(continent) %>%
        summarize(summ=list(c(summary(lifeExp) %>% round(digits=1)))) %>%
        unnest_wider(summ)

```


```{r opt_3_graph}

o3g <- gapminder %>%
  group_by(continent) %>%
  ggplot(aes(x=continent,y=gdpPercap, colour=continent)) +
  geom_jitter() +
  scale_y_log10(labels=scales::dollar_format()) +
  labs(x="",
       y="GDP per capita, US $ (inflation-adjusted)",
       colour="Continent")

```
<div class="twoC">
```{r opt_3_output, echo=F}

knitr::kable(o3)
o3g

```
</div>
<div class="clearer"></div>



### Task Option 6
##### Find countries with interesting stories.

```{r opt_6_data, warning=F, message=F}

#main dataframe for all countries, this is what to graph by
df1 <- gapminder %>%
            group_by(country) %>%
            arrange(year) %>%
            mutate(popChg = tsibble::difference(pop),
                   popChg.pc = tsibble::difference(pop)/pop*100 %>% round(digits=1)) %>%
            drop_na() 
#make a summary dataframe of selected countries and mean of all others
df2 <- df1 %>%
      mutate(Group = ifelse(country=="Kuwait","KW", 
                              ifelse(country=="Equatorial Guinea", "EG", "All"))) %>%
      group_by(Group) %>%
      summarize(chg_1957=mean(popChg.pc[year==1957]) %>% round(1),
                chg_1962=mean(popChg.pc[year==1962]) %>% round(1),
                chg_1967=mean(popChg.pc[year==1967]) %>% round(1),
                chg_1972=mean(popChg.pc[year==1972]) %>% round(1),
                chg_1977=mean(popChg.pc[year==1977]) %>% round(1),
                chg_1982=mean(popChg.pc[year==1982]) %>% round(1),
                chg_1987=mean(popChg.pc[year==1987]) %>% round(1),
                chg_1992=mean(popChg.pc[year==1992]) %>% round(1),
                chg_1997=mean(popChg.pc[year==1997]) %>% round(1),
                chg_2002=mean(popChg.pc[year==2002]) %>% round(1), #its too wide for side-by-side
                chg_2007=mean(popChg.pc[year==2007]) %>% round(1)) #so must transpose below
    
#transposing the data... there must be an easier way
o6 <- df2 %>%
        t() %>% #transpose
        cbind(meanPopChg_Year=names(df2)) %>% #add a names column containing the years
        as_tibble(.name_repair="universal") %>% #make tibble, pre-slice because slice only works on tibble
        slice(-1) %>% #take out the first row, which does not have data
        rename(Other=...1, Eq_Guinea=...2, Kuwait=...3) %>% #rename the other columns
        select(meanPopChg_Year, everything()) %>% #move the ID column to the left
        select(-Other, Other) %>% #move Other to end, match legend order
        mutate_at(.vars=1, .funs=funs(substr(.,nchar(.)-3,nchar(.)))) %>% #keep just the year
        mutate_at(1:4, as.numeric) #change the column classes back to numeric

```

```{r opt_6 graph}


#filtered dataframes for countries of interest
df.eg <- df1 %>% filter(country=="Equatorial Guinea")
df.kw <- df1 %>% filter(country=="Kuwait")

#plot it all together
o6g <-  df1 %>%
          ggplot(aes(y=popChg.pc,x=year,group=country)) +
            geom_line(aes(colour="grey"), alpha=0.3) +
            geom_line(data=df.eg, 
                      aes(y=popChg.pc,x=year,group=country,colour="firebrick4"),  
                      alpha=1, size=1.1) +
            geom_line(data=df.kw, 
                      aes(y=popChg.pc,x=year,group=country, colour="darkslategray4"), 
                      alpha=1, size=1.1) +
            scale_colour_manual(name="Countries", #for colours to be used in legend they need to be called in aes() within geom() functions
                                values=c("darkslategray4","firebrick4","grey"), #order apprently needs to be in reverse of when called
                                labels=c("Kuwait","Equatorial Guinea","Other")) + 
            theme_bw() +
            labs(title="Kuwait and Equatorial Guinea have had major population \n fluctuations due to armed conflict", #\n for line break
                 x="",
                 y="5-year population change (%)")
```

<div class="twoC">
```{r opt_6_display, echo=F}
#DT::datatable(o6)
knitr::kable(o6)
o6g

```
</div>
<div class="clearer"></div>

